### ISSUE TITLE
Does this client work on mac os?

### ISSUE THREAD

**Issue by divohub** [ascpixi/splicedd#11]
I tried to build a macOS version using a workflow like this,
but it seems drag & drop doesn’t work on Mac — maybe I built it wrong.

What do you think — is it possible to make a proper macOS version?

btw this client is great, thank you!
```
name: Build macOS DMG

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install app dependencies
        run: npm install

      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Build DMG
        run: npm run tauri build

      - name: Upload DMG artifact
        uses: actions/upload-artifact@v4
        with:
          name: splicedd-macos-dmg
          path: src-tauri/target/release/bundle/dmg/*.dmg
```
